CREATE TABLE contact_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    testimonial_id BIGINT NOT NULL REFERENCES testimonial (id) ON DELETE CASCADE,
    contact_type_id BIGINT NOT NULL REFERENCES contact_type (id),
    value VARCHAR(500) NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL
);
