-- Topic catalog seed data, transcribed verbatim from docs/use-cases.md's
-- "Topic catalog" table (decision 11). The doc's table gives only Group /
-- Tag slug / Guiding prompt columns -- it has no separate "label" column,
-- so each Topic.label below is a concise label derived from its guiding
-- prompt (same derivation approach the doc calls for on Achievement slugs).
-- display_order: TopicGroup rows and standalone Topic rows share one
-- combined top-level ordering (1-17, the table's own row order); grouped
-- Topic rows are ordered 1..N within their own group.

INSERT INTO topic_group (id, label, display_order) VALUES
    (1, 'Academics', 1),
    (2, 'Housing & Food', 2),
    (3, 'Travel', 3),
    (4, 'Campus Life', 4),
    (5, 'OGE / International Office', 5),
    (6, 'Cultural Adaptation', 6),
    (7, 'Practicalities', 14),
    (8, 'Health & Wellbeing', 15),
    (9, 'Reflection', 16);

-- Explicit-id inserts above don't advance a GENERATED BY DEFAULT identity's
-- internal counter (on either H2 or Postgres), so any later auto-generated
-- insert (e.g. via catalogadmin) would otherwise collide with ids 1-9.
ALTER TABLE topic_group ALTER COLUMN id RESTART WITH 10;

-- Academics (topic_group_id = 1)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (1, 'academics_teaching', 'Teaching Quality', 'How would you describe the teaching quality of the professors you had?', 1),
    (1, 'academics_difficulty', 'Course Difficulty', 'Were the courses challenging, easy, or about what you expected?', 2),
    (1, 'academics_style', 'Academic Style', 'How different was the academic style here vs. your home university?', 3),
    (1, 'academics_standout', 'Standout Course or Professor', 'Any standout course or professor you''d recommend?', 4),
    (1, 'academics_support', 'Professor Support', 'How supportive were professors outside of class (office hours, mentorship)?', 5),
    (1, 'academics_credits', 'Credit Transfer', 'Any bureaucratic hurdles getting course credits recognized back home?', 6),
    (1, 'academics_workload', 'Workload', 'Was the workload manageable alongside exploring campus/city life?', 7),
    (1, 'academics_library', 'Library & Study Spaces', 'How were the library and study spaces?', 8);

-- Housing & Food (topic_group_id = 2)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (2, 'housing_accommodation', 'Accommodation', 'What was your accommodation (hostel/dorm) like?', 1),
    (2, 'housing_recommend', 'Housing Recommendation', 'Would you recommend the campus housing, or suggest looking elsewhere?', 2),
    (2, 'housing_food', 'Mess/Canteen Food', 'How was the food in the mess/canteen?', 3),
    (2, 'housing_discovery', 'Favorite Food Discovery', 'What was your favorite local food discovery?', 4);

-- Travel (topic_group_id = 3)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (3, 'travel_did', 'Travel Experiences', 'Did you manage to travel — within India, to neighboring countries, or both?', 1),
    (3, 'travel_recommend', 'Recommended Trip', 'What''s one trip you''d recommend to a future exchange student?', 2),
    (3, 'travel_ease', 'Ease of Traveling', 'How easy or affordable was traveling around while studying?', 3);

-- Campus Life (topic_group_id = 4)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (4, 'campus_events', 'Campus Events & Festivals', 'What campus events or festivals did you take part in?', 1),
    (4, 'campus_clubs', 'Clubs & Sports Teams', 'Did you join any clubs, sports teams, or student organizations?', 2),
    (4, 'campus_atmosphere', 'Social Atmosphere', 'How was the social atmosphere on campus?', 3),
    (4, 'campus_hobbies', 'Extracurricular Hobbies', 'What extracurricular skills or hobbies did you pick up?', 4);

-- OGE / International Office (topic_group_id = 5)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (5, 'oge_support', 'OGE Support', 'How was your experience with the International Relations office (OGE) — visas, paperwork, onboarding?', 1),
    (5, 'oge_gaps', 'Admin Process Gaps', 'Anything about the admin process you wish you''d known beforehand?', 2),
    (5, 'oge_emergencies', 'Emergency Responsiveness', 'How responsive was IITM to any problems or emergencies you had?', 3);

-- Cultural Adaptation (topic_group_id = 6)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (6, 'adapt_shock', 'Culture Shock', 'What was the biggest culture shock or adjustment?', 1),
    (6, 'adapt_weather', 'Weather Adaptation', 'How did you adapt to the local weather/climate?', 2),
    (6, 'adapt_language', 'Language Barrier', 'How was the language barrier, if any?', 3),
    (6, 'adapt_surprise', 'Biggest Surprise', 'What surprised you most about daily life in Chennai?', 4);

-- Standalone topics (topic_group_id = NULL), first batch — display_order
-- continues the combined top-level sequence (7-13).
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (NULL, 'new_friendships', 'New Friendships', 'Did you make new friends here?', 7),
    (NULL, 'romance', 'Romance', 'Did you find love or start a relationship during your exchange?', 8),
    (NULL, 'networking', 'Professional Networking', 'Did you build valuable professional connections or a network?', 9),
    (NULL, 'career', 'Career Impact', 'Did this experience affect your career plans, skills, or job opportunities?', 10),
    (NULL, 'contacts', 'Lasting Contacts', 'Did you make contacts you plan to stay in touch with, or who could help future exchange students?', 11),
    (NULL, 'opportunities', 'Other Opportunities', 'Any other opportunities (jobs, scholarships, further exchange, projects) that came out of this experience?', 12),
    (NULL, 'social_compatriots', 'Compatriots on Campus', 'How easy was it to find people from your own country on campus?', 13);

-- Practicalities (topic_group_id = 7)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (7, 'practical_cost', 'Cost of Living', 'How would you describe the cost of living?', 1),
    (7, 'practical_transport', 'Getting Around', 'What was getting around the city/campus like?', 2),
    (7, 'practical_internet', 'Internet & Connectivity', 'How was the internet/mobile connectivity on campus?', 3),
    (7, 'practical_safety', 'Safety', 'Any safety concerns or tips for future students?', 4),
    (7, 'practical_budget', 'Budgeting Tips', 'Any tips on budgeting for the semester?', 5),
    (7, 'practical_packing', 'Packing Tips', 'What would you pack differently if you were doing it again?', 6);

-- Health & Wellbeing (topic_group_id = 8)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (8, 'health_care', 'Healthcare & Medical Support', 'How was the healthcare/medical support if you needed it?', 1),
    (8, 'health_homesick', 'Homesickness', 'Did you experience any homesickness, and how did you deal with it?', 2);

-- Reflection (topic_group_id = 9)
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (9, 'reflect_before', 'What I Wish I Knew', 'What''s the one thing you wish you knew before coming?', 1),
    (9, 'reflect_again', 'Would You Do It Again?', 'Would you do it again, and why (or why not)?', 2),
    (9, 'reflect_memory', 'Best Memory', 'What''s your single best memory from the exchange?', 3),
    (9, 'reflect_advice', 'Advice for Future Students', 'What would you tell someone considering IITM for exchange?', 4);

-- Mandatory standalone catch-all (topic_group_id = NULL), last of the 17
-- top-level picks.
INSERT INTO topic (topic_group_id, slug, label, guiding_prompt, display_order) VALUES
    (NULL, 'general', 'General', 'Anything else you''d like to add. (mandatory catch-all)', 17);
