CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_group_id BIGINT NULL REFERENCES topic_group (id),
    slug VARCHAR NOT NULL UNIQUE,
    label VARCHAR NOT NULL,
    guiding_prompt VARCHAR NOT NULL,
    display_order INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);
