CREATE TABLE testimonial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    roll_number VARCHAR NOT NULL,
    admission_year INT NOT NULL,
    email VARCHAR(500) NOT NULL,
    email_lookup_hash VARCHAR NOT NULL UNIQUE,
    country_code VARCHAR(2) NOT NULL REFERENCES country (code),
    recommendation_score INT NOT NULL CHECK (recommendation_score BETWEEN 0 AND 10),
    data_processing_consent BOOLEAN NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE NULL,
    rejected_at TIMESTAMP WITH TIME ZONE NULL,
    identity_modified BOOLEAN NOT NULL DEFAULT FALSE,
    score_modified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_testimonial_status_country ON testimonial (status, country_code);
