CREATE TABLE testimonial_section (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    testimonial_id BIGINT NOT NULL REFERENCES testimonial (id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES topic (id),
    answer_text VARCHAR NOT NULL,
    modified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_testimonial_section_topic ON testimonial_section (topic_id);
