CREATE TABLE photo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    testimonial_section_id BIGINT NOT NULL REFERENCES testimonial_section (id) ON DELETE CASCADE,
    file_path VARCHAR NOT NULL,
    display_order INT NOT NULL
);
