CREATE TABLE photo_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id BIGINT NOT NULL REFERENCES photo (id) ON DELETE CASCADE,
    tag_text VARCHAR NOT NULL,
    CONSTRAINT uk_photo_tag_photo_id_tag_text UNIQUE (photo_id, tag_text)
);
